### ISSUE TITLE
include CPCEM.h -> CPCem.h

### ISSUE THREAD

**Issue by issalig** [rpsubc8/ESP32TinyCPC#2]
Hola, bajo el ide de arduino (supongo que en platformio tb) en Linux hay que cambiar los includes de CPCEM.h a  CPCem.h  o bien renombrar el fichero CPCEM.h a CPCem.h

Enhorabuena por el curro.

**Comment by rpsubc8** [comment]
Muchas gracias. 
Culpa mia, que me acostumbro a Windows con los nombres.
He cambiado los includes de CPCEM.h a CPCem.h, y subido al repositorio. Si no me he equivocado, estaría arreglado.
Saludos.

**Comment by issalig** [comment]
Comprobado. Funciona en Linux.
