### ISSUE TITLE
Poder usar una SD para poner las ROMS

### ISSUE THREAD

**Issue by yako1984** [rpsubc8/ESP32TinyCPC#3]
La idea sería adaptar el código, para poder usar una SD para poner las ROMS. Hay un usuario de GitHub que lo hizo con un emulador de ZX spectrum con esta mismo hardware y dice que es facil. https://github.com/dcrespo3d/ZX-ESPectrum-Wiimote/tree/master/docs/my-esp32-history-es

**Comment by rpsubc8** [comment]
Gracias.
Al desarrollador dcrespo3d, que ha realizado un excelente trabajo, lo conozco, dado que compartimos ideas y código del emulador ZX ESPectrum. 
Este proyecto va enfocado a placas simples ESP32, como TTGO VGA32 v1.2 o el Arduino UNO d1 r32, que al carecer de PSRAM y de módulo SD, no he añadido dicha utilidad de SD. Así mismo, al no usar ningún módulo adicional, me permite disponer de más SRAM, incluso de hacer uso de la RTC RAM. Si se usa un módulo WIFI o algún módulo adicional, no se puede usar la RTC RAM.
Añadir la funcionalidad de SD es muy fácil, y dado que he dejado el código disponible, sin ningún tipo de licencia restrictiva, cualquiera puede añadirlo.

**Comment by SanPollo** [comment]
@rpsubc8 quiero mucho añadir el código para la SD pero no sé como (no soy programador). Podrías escribir unas intrucciones para nosotros por favor?

**Comment by rpsubc8** [comment]
> @rpsubc8 quiero mucho añadir el código para la SD pero no sé como (no soy programador). Podrías escribir unas intrucciones para nosotros por favor?

Puedes mirar el fork que ha realizado el usuario elfuska:
https://github.com/elfuska/ESP32TinyCPC

También puedes visitar los foros sobre desarrollos en ESP32 y plantear ahí las dudas:
https://www.retrowiki.es/viewforum.php?f=114
