### ISSUE TITLE
Device in Arduino IDE ?

### ISSUE THREAD

**Issue by AxelAhlborn** [rpsubc8/ESP32TinyCPC#4]
Hello, which device do I select in the Arduino IDE to program the ttgo-vga?

Greetings Axel

**Comment by rpsubc8** [comment]
The ESP32 DEV Module is sufficient, but you can also select the ESP32 Pico Kit.

**Comment by AxelAhlborn** [comment]
The ESP32 DEV says: Sketch too big. I will try the TTGO T7 V1.4 Mini32.Greetings Axel

**Comment by AxelAhlborn** [comment]
TTGO T7 V1.4 is still working. The sketch is running :-)

**Comment by rpsubc8** [comment]
Partition Scheme Huge APP should be selected, as it uses more than 1 MB and disable PSRAM.
