### ISSUE TITLE
Keyboard Mapping

### ISSUE THREAD

**Issue by AxelAhlborn** [rpsubc8/ESP32TinyCPC#5]
Hello, where do I find the " on the keyboard. I use a german keyboard. Greetings Axel

**Comment by rpsubc8** [comment]
The project uses the basic keymap.  In Spanish, if you press the (right shift key)+(key number 2) the (") appears. It has to be the (right shift key), not the (left shift). All the key translation is in the SDL_keys_poll function of CPCem.ino, so it is very easy to modify it to your liking.
