### ISSUE TITLE
Gettting the code to fit in the LILYGO

### ISSUE THREAD

**Issue by souphead** [rpsubc8/ESP32TinyCPC#6]
I've been trying to get this to compile (and fit) in the LILYGO VGA 1.4 on the Arduino IDE. The compile seems OK but it says it takes up 135% of the maximum storage space. I tried changing some of the configuration options but it remained at 135%. The doc said use FabGL 0.9.0, so I removed my usual 1.0.9 version and added 0.9.0 and recompiled. Same 135% of max size.

Generally everything else I compile with FabGL and Arduino IDE on my LILYGO VGA seems to work OK.

Any idea what I am doing wrong?

**Comment by rpsubc8** [comment]
The project uses the modified reduced version of fabgl soundgen 0.9.0 for sound (included), so you don't need to have any version of fabgl installed on the Arduino IDE or PlatformIO.
The failure you are getting is due to limited free space in flash. To do this from Arduino IDE you have to choose in:
 tools --> Partition Scheme (Huge App).
Also make sure you have PSRAM disabled.

**Comment by souphead** [comment]
I got it working. I guess for anyone that uses the LILYGO VGA with Arduino and has it set up more conventionally, you need to do the following:
Instead of picking the TTGO V7 1.4 mini32 board, pick the "ESP32 Dev Module", **NOT the ESP32S3 Dev Module**. With that, pick the "Huge APP" partition scheme and the PSRAM option will be there which does default to DISABLED. Other than that it is a straight compile and load.

The only issues I has are with the keyboard layout which looks like the standard CPC464 layout. It make perfect sense but not too close to my US keyboard. I guess I may have to "dedicate" an old PS/2 keyboard and scratch off and re-dedicate the keys. What was the reason for the left and right shifts working differently?

As far as I can tell my 1.0.9 copy of FabGL seems to work for the sound card too.

Great job!
